version: '3.8'

services:
  tika:
    build: .
    ports:
      - "9998:9998"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s